language: cpp

matrix:
  include:
  - name: "Clang on Linux (Debug)"
    os: linux
    compiler: clang
    script:
    - ./build.sh --clean -d

  - name: "Clang on Linux (Release)"
    os: linux
    compiler: clang
    before_install:
    - git clone https://github.com/emscripten-core/emsdk.git
    - cd emsdk
    - ./emsdk install latest
    - ./emsdk activate latest
    - source ./emsdk_env.sh
    - cd ..
    script:
    - ./build.sh --clean -r

  - name: "Clang on OS X (Debug)"
    os: osx
    compiler: clang
    script:
    - ./build.sh --clean -d

  - name: "Clang on OS X (Release)"
    os: osx
    compiler: clang
    script:
    - ./build.sh --clean -r

  - name: "Visual C++ on Windows (Debug)"
    os: windows
    script:
    - ./build.sh --clean -d

  - name: "Visual C++ on Windows (Release)"
    os: windows
    script:
    - ./build.sh --clean -r
