language: cpp

matrix:
  include:
  - name: "Clang on Linux (Debug)"
    os: linux
    compiler: clang
    script:
    - ./build.sh --clean -d

  - name: "Clang on OS X (Debug)"
    os: osx
    compiler: clang
    script:
    - ./build.sh --clean -d

  - name: "Visual C++ on Windows (Debug)"
    os: windows
    script:
    - ./build.sh --clean -d
