language: cpp

matrix:
  include:
  - name: "Clang on Linux (Debug)"
    os: linux
    compiler: clang
    addons:
      apt:
        packages:
        - libboost-test-dev
    script:
    - ./build.sh --clean -d

  - name: "Clang on OS X (Debug)"
    os: osx
    compiler: clang
    script:
    - ./build.sh --clean -d

  - name: "Clang on Windows (Debug)"
    os: windows
    compiler: clang
    script:
    - ./build.sh --clean -d
