language: cpp

matrix:
  include:
  - name: "Clang on Linux (Debug)"
    os: linux
    compiler: clang
    script:
    - ./build.sh --clean -t Debug

  - name: "Clang on OS X (Debug)"
    os: osx
    compiler: clang
    script:
    - ./build.sh --clean -t Debug

  - name: "Clang on Windows (Debug)"
    os: windows
    compiler: clang
    script:
    - cmd /c "./build.bat /c"
