name: ci
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
      - name: Build
        run: bazel --bazelrc=.github/github.bazelrc build //...
      - name: Test
        run: bazel --bazelrc=.github/github.bazelrc test //...
